# Generated by Django 5.0.3 on 2024-04-12 14:39

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('acc', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlaygroundCode',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code_unique_name', models.CharField(max_length=2000)),
                ('user_code', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user_obj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='acc.customuser')),
            ],
        ),
        migrations.CreateModel(
            name='PlaygroundConversation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('question', models.CharField(max_length=3000)),
                ('question_prompt', models.TextField()),
                ('response', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('code_obj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learning_assistant.playgroundcode')),
            ],
        ),
    ]
