# Generated by Django 5.0.3 on 2024-03-28 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_assistant', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercode',
            name='unique_anon_user_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='userconversation',
            name='unique_anon_user_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='usergeneraltutorconversation',
            name='user_anon_unique_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
