# Generated by Django 5.0.3 on 2024-04-14 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning_assistant', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatconversation',
            name='user_obj',
        ),
    ]
