# Generated by Django 5.0.3 on 2024-04-20 23:59

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acc', '0001_initial'),
        ('learning_assistant', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PythonCourseModuleParent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='PythonCourseExercise',
            fields=[
                ('pythoncoursemoduleparent_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='learning_assistant.pythoncoursemoduleparent')),
                ('exercise', models.TextField()),
                ('complete', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(auto_now=True)),
            ],
            bases=('learning_assistant.pythoncoursemoduleparent',),
        ),
        migrations.CreateModel(
            name='PythonCourseNote',
            fields=[
                ('pythoncoursemoduleparent_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='learning_assistant.pythoncoursemoduleparent')),
                ('note', models.TextField()),
            ],
            bases=('learning_assistant.pythoncoursemoduleparent',),
        ),
        migrations.CreateModel(
            name='PythonCourseStudentBackground',
            fields=[
                ('pythoncoursemoduleparent_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='learning_assistant.pythoncoursemoduleparent')),
                ('student_background', models.TextField()),
            ],
            bases=('learning_assistant.pythoncoursemoduleparent',),
        ),
        migrations.CreateModel(
            name='PythonCourseParent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user_obj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='acc.customuser')),
            ],
        ),
        migrations.AddField(
            model_name='pythoncoursemoduleparent',
            name='pg_obj',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learning_assistant.pythoncourseparent'),
        ),
        migrations.CreateModel(
            name='PythonCourseConversation',
            fields=[
                ('chatconversation_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='learning_assistant.chatconversation')),
                ('pg_obj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learning_assistant.pythoncourseparent')),
            ],
            bases=('learning_assistant.chatconversation',),
        ),
    ]
