# Generated by Django 5.0.3 on 2024-04-21 19:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_assistant', '0002_pythoncoursemoduleparent_pythoncourseexercise_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PythonCourseStudentOutline',
            fields=[
                ('pythoncoursemoduleparent_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='learning_assistant.pythoncoursemoduleparent')),
                ('json_response', models.TextField()),
            ],
            bases=('learning_assistant.pythoncoursemoduleparent',),
        ),
    ]
