# Generated by Django 5.0.3 on 2024-03-28 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning_assistant', '0002_usercode_unique_anon_user_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usergeneraltutorconversation',
            old_name='user_anon_unique_id',
            new_name='unique_anon_user_id',
        ),
    ]
