# Generated by Django 5.0.3 on 2024-04-29 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_assistant', '0002_playgroundcode_user_code_output'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatconversation',
            name='prompt_token_count',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
