# Generated by Django 5.0.3 on 2024-04-14 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning_assistant', '0002_remove_chatconversation_user_obj'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usergeneraltutorconversation',
            name='unique_anon_user_id',
        ),
        migrations.RemoveField(
            model_name='usergeneraltutorparent',
            name='unique_anon_user_id',
        ),
    ]
