# Generated by Django 5.0.3 on 2024-04-22 00:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_assistant', '0003_pythoncoursestudentoutline'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pythoncoursestudentoutline',
            name='json_response',
        ),
        migrations.AddField(
            model_name='pythoncoursestudentoutline',
            name='course_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pythoncoursestudentoutline',
            name='course_name',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pythoncoursestudentoutline',
            name='module_list',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pythoncoursestudentoutline',
            name='student_background',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='PythonCourseStudentModuleChild',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module_number', models.IntegerField()),
                ('module_topic', models.TextField()),
                ('module_description', models.TextField()),
                ('std_outline_obj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='learning_assistant.pythoncoursestudentoutline')),
            ],
        ),
        migrations.DeleteModel(
            name='PythonCourseStudentBackground',
        ),
    ]
