# Generated by Django 5.0.3 on 2024-03-29 21:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_assistant', '0003_rename_user_anon_unique_id_usergeneraltutorconversation_unique_anon_user_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserGeneralTutorParent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_anon_user_id', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user_auth_obj', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='learning_assistant.useroauth')),
            ],
        ),
        migrations.AddField(
            model_name='usergeneraltutorconversation',
            name='chat_parent_object',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='learning_assistant.usergeneraltutorparent'),
        ),
    ]
