# Generated by Django 5.0.3 on 2024-04-06 02:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_assistant', '0005_chatconversation_userbackgroundparent_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=3000)),
                ('description', models.TextField()),
                ('outline', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('initial_background_object', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='learning_assistant.userbackgroundparent')),
            ],
        ),
        migrations.CreateModel(
            name='UserCourseOutlineConversation',
            fields=[
                ('chatconversation_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='learning_assistant.chatconversation')),
                ('course_parent_object', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='learning_assistant.usercourse')),
            ],
            bases=('learning_assistant.chatconversation',),
        ),
    ]
