# Generated by Django 5.0.3 on 2024-04-06 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_assistant', '0006_usercourse_usercourseoutlineconversation'),
    ]

    operations = [
        migrations.AddField(
            model_name='userbackgroundconversation',
            name='model_response_is_final_message',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userbackgroundconversation',
            name='model_response_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
