# Generated by Django 5.0.3 on 2024-04-06 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_assistant', '0007_userbackgroundconversation_model_response_is_final_message_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercourse',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
