# Generated by Django 5.0.3 on 2024-04-07 15:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_assistant', '0008_usercourse_updated_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usercourse',
            old_name='outline',
            new_name='module_list',
        ),
        migrations.CreateModel(
            name='UserCourseModules',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module_topic', models.TextField()),
                ('module_description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('parent_course_object', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='learning_assistant.usercourse')),
            ],
        ),
        migrations.CreateModel(
            name='UserCourseNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_parent_object', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='learning_assistant.usercourse')),
            ],
        ),
    ]
