# Generated by Django 5.0.3 on 2024-04-07 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_assistant', '0009_rename_outline_usercourse_module_list_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercoursemodules',
            name='module_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
