# Generated by Django 5.0.3 on 2024-04-07 23:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_assistant', '0010_usercoursemodules_module_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserCourseModuleConversation',
            fields=[
                ('chatconversation_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='learning_assistant.chatconversation')),
                ('course_module_object', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='learning_assistant.usercoursemodules')),
            ],
            bases=('learning_assistant.chatconversation',),
        ),
        migrations.CreateModel(
            name='UserCourseModuleNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes_md', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course_module_object', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='learning_assistant.usercoursemodules')),
            ],
        ),
        migrations.DeleteModel(
            name='UserCourseNote',
        ),
    ]
