# Generated by Django 5.0.3 on 2024-04-08 01:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_assistant', '0011_usercoursemoduleconversation_usercoursemodulenote_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserCourseModuleNoteQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_number', models.IntegerField()),
                ('question', models.TextField()),
                ('answer', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course_note_object', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='learning_assistant.usercoursemodulenote')),
            ],
        ),
    ]
