# Generated by Django 5.0.3 on 2024-04-10 15:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_assistant', '0013_usercoursemodulenotequestion_multiple_choice_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserCourseModulesBingResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('url', models.TextField()),
                ('snippet', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('parent_course_object', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='learning_assistant.usercourse')),
            ],
        ),
    ]
