# Generated by Django 5.0.3 on 2024-04-14 18:01

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnonUser',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='UserOAuth',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('auth_type', models.CharField(max_length=500)),
                ('email', models.EmailField(max_length=254)),
                ('email_verified', models.BooleanField()),
                ('name', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('anon_user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='acc.anonuser')),
                ('oauth_user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='acc.useroauth')),
            ],
        ),
    ]
